//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDokServiceV1.DAL
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dokument", Namespace="http://schemas.datacontract.org/2004/07/WCFDokServiceV1.DAL")]
    public partial class Dokument : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DokAngelegtAmField;
        
        private string DokAutorField;
        
        private int DokIdField;
        
        private string DokTitelField;
        
        private WCFDokServiceV1.DAL.MediaType MedientypField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DokAngelegtAm
        {
            get
            {
                return this.DokAngelegtAmField;
            }
            set
            {
                this.DokAngelegtAmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DokAutor
        {
            get
            {
                return this.DokAutorField;
            }
            set
            {
                this.DokAutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DokId
        {
            get
            {
                return this.DokIdField;
            }
            set
            {
                this.DokIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DokTitel
        {
            get
            {
                return this.DokTitelField;
            }
            set
            {
                this.DokTitelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFDokServiceV1.DAL.MediaType Medientyp
        {
            get
            {
                return this.MedientypField;
            }
            set
            {
                this.MedientypField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaType", Namespace="http://schemas.datacontract.org/2004/07/WCFDokServiceV1.DAL")]
    public enum MediaType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfDokument = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OfficeDokument = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sonstiges = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ef/documents", ConfigurationName="IDokumentService")]
public interface IDokumentService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ef/documents/IDokumentService/GetDokumente", ReplyAction="http://ef/documents/IDokumentService/GetDokumenteResponse")]
    WCFDokServiceV1.DAL.Dokument[] GetDokumente();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ef/documents/IDokumentService/GetDokumente", ReplyAction="http://ef/documents/IDokumentService/GetDokumenteResponse")]
    System.Threading.Tasks.Task<WCFDokServiceV1.DAL.Dokument[]> GetDokumenteAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ef/documents/IDokumentService/GetDokument", ReplyAction="http://ef/documents/IDokumentService/GetDokumentResponse")]
    WCFDokServiceV1.DAL.Dokument GetDokument(int DokId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ef/documents/IDokumentService/GetDokument", ReplyAction="http://ef/documents/IDokumentService/GetDokumentResponse")]
    System.Threading.Tasks.Task<WCFDokServiceV1.DAL.Dokument> GetDokumentAsync(int DokId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ef/documents/IDokumentService/SearchDokumente", ReplyAction="http://ef/documents/IDokumentService/SearchDokumenteResponse")]
    WCFDokServiceV1.DAL.Dokument[] SearchDokumente(string Filter);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ef/documents/IDokumentService/SearchDokumente", ReplyAction="http://ef/documents/IDokumentService/SearchDokumenteResponse")]
    System.Threading.Tasks.Task<WCFDokServiceV1.DAL.Dokument[]> SearchDokumenteAsync(string Filter);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDokumentServiceChannel : IDokumentService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DokumentServiceClient : System.ServiceModel.ClientBase<IDokumentService>, IDokumentService
{
    
    public DokumentServiceClient()
    {
    }
    
    public DokumentServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DokumentServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DokumentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DokumentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WCFDokServiceV1.DAL.Dokument[] GetDokumente()
    {
        return base.Channel.GetDokumente();
    }
    
    public System.Threading.Tasks.Task<WCFDokServiceV1.DAL.Dokument[]> GetDokumenteAsync()
    {
        return base.Channel.GetDokumenteAsync();
    }
    
    public WCFDokServiceV1.DAL.Dokument GetDokument(int DokId)
    {
        return base.Channel.GetDokument(DokId);
    }
    
    public System.Threading.Tasks.Task<WCFDokServiceV1.DAL.Dokument> GetDokumentAsync(int DokId)
    {
        return base.Channel.GetDokumentAsync(DokId);
    }
    
    public WCFDokServiceV1.DAL.Dokument[] SearchDokumente(string Filter)
    {
        return base.Channel.SearchDokumente(Filter);
    }
    
    public System.Threading.Tasks.Task<WCFDokServiceV1.DAL.Dokument[]> SearchDokumenteAsync(string Filter)
    {
        return base.Channel.SearchDokumenteAsync(Filter);
    }
}
