//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDokServerV1GUIClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dokument", Namespace="http://schemas.datacontract.org/2004/07/WCFDokServiceV1.DAL")]
    [System.SerializableAttribute()]
    public partial class Dokument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DokAngelegtAmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DokAutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DokIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DokTitelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFDokServerV1GUIClient.ServiceReference1.MediaType MedientypField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DokAngelegtAm {
            get {
                return this.DokAngelegtAmField;
            }
            set {
                if ((this.DokAngelegtAmField.Equals(value) != true)) {
                    this.DokAngelegtAmField = value;
                    this.RaisePropertyChanged("DokAngelegtAm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DokAutor {
            get {
                return this.DokAutorField;
            }
            set {
                if ((object.ReferenceEquals(this.DokAutorField, value) != true)) {
                    this.DokAutorField = value;
                    this.RaisePropertyChanged("DokAutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DokId {
            get {
                return this.DokIdField;
            }
            set {
                if ((this.DokIdField.Equals(value) != true)) {
                    this.DokIdField = value;
                    this.RaisePropertyChanged("DokId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DokTitel {
            get {
                return this.DokTitelField;
            }
            set {
                if ((object.ReferenceEquals(this.DokTitelField, value) != true)) {
                    this.DokTitelField = value;
                    this.RaisePropertyChanged("DokTitel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFDokServerV1GUIClient.ServiceReference1.MediaType Medientyp {
            get {
                return this.MedientypField;
            }
            set {
                if ((this.MedientypField.Equals(value) != true)) {
                    this.MedientypField = value;
                    this.RaisePropertyChanged("Medientyp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaType", Namespace="http://schemas.datacontract.org/2004/07/WCFDokServiceV1.DAL")]
    public enum MediaType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PdfDokument = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OfficeDokument = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sonstiges = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ef/documents", ConfigurationName="ServiceReference1.IDokumentService")]
    public interface IDokumentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ef/documents/IDokumentService/GetDokumente", ReplyAction="http://ef/documents/IDokumentService/GetDokumenteResponse")]
        WCFDokServerV1GUIClient.ServiceReference1.Dokument[] GetDokumente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ef/documents/IDokumentService/GetDokument", ReplyAction="http://ef/documents/IDokumentService/GetDokumentResponse")]
        WCFDokServerV1GUIClient.ServiceReference1.Dokument GetDokument(int DokId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ef/documents/IDokumentService/SearchDokumente", ReplyAction="http://ef/documents/IDokumentService/SearchDokumenteResponse")]
        WCFDokServerV1GUIClient.ServiceReference1.Dokument[] SearchDokumente(string Filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDokumentServiceChannel : WCFDokServerV1GUIClient.ServiceReference1.IDokumentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DokumentServiceClient : System.ServiceModel.ClientBase<WCFDokServerV1GUIClient.ServiceReference1.IDokumentService>, WCFDokServerV1GUIClient.ServiceReference1.IDokumentService {
        
        public DokumentServiceClient() {
        }
        
        public DokumentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DokumentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DokumentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DokumentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFDokServerV1GUIClient.ServiceReference1.Dokument[] GetDokumente() {
            return base.Channel.GetDokumente();
        }
        
        public WCFDokServerV1GUIClient.ServiceReference1.Dokument GetDokument(int DokId) {
            return base.Channel.GetDokument(DokId);
        }
        
        public WCFDokServerV1GUIClient.ServiceReference1.Dokument[] SearchDokumente(string Filter) {
            return base.Channel.SearchDokumente(Filter);
        }
    }
}
